### ISSUE TITLE
ImportError when using pynng `v0.8.0` on osx-arm64

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [conda-forge/pynng-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When trying to import the conda-forge version of `pynng` on `osx-arm64`, an error occurs:

```
>>> import pynng
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/Users/thomasmarwitz/mambaforge/envs/pipdag/lib/python3.12/site-packages/pynng/__init__.py", line 3, in <module>
  from ._nng import lib, ffi
ImportError: dlopen(/Users/thomasmarwitz/mambaforge/envs/pipdag/lib/python3.12/site-packages/pynng/_nng.abi3.so, 0x0002): symbol not found in flat namespace '_nng_aio_abort'
```

### Installed packages

```shell
Name                      Version                   Build    Channel
bzip2                     1.0.8                h93a5062_5    conda-forge
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cffi                      1.16.0          py311h4a08483_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.44.2               h091b4b1_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
mbedtls                   3.3.0                hb7217d7_0    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
nng                       1.6.0                hebf3989_3    conda-forge
openssl                   3.2.0                h0d3ecfb_1    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pynng                     0.8.0           py311h92babd0_0    conda-forge
python                    3.11.7          hdf0ec26_1_cpython    conda-forge
python_abi                3.11                    4_cp311    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```

### Environment info

```shell
active environment : pynng
    active env location : /Users/thomasmarwitz/mambaforge/envs/pynng
            shell level : 2
       user config file : /Users/thomasmarwitz/.condarc
 populated config files : /Users/thomasmarwitz/mambaforge/.condarc
                          /Users/thomasmarwitz/.condarc
          conda version : 23.10.0
    conda-build version : 3.27.0
         python version : 3.9.18.final.0
       virtual packages : __archspec=1=m2
                          __osx=14.1.1=0
                          __unix=0=0
       base environment : /Users/thomasmarwitz/mambaforge  (writable)
      conda av data dir : /Users/thomasmarwitz/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/thomasmarwitz/mambaforge/pkgs
                          /Users/thomasmarwitz/.conda/pkgs
       envs directories : /Users/thomasmarwitz/mambaforge/envs
                          /Users/thomasmarwitz/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.9.18 Darwin/23.1.0 OSX/14.1.1 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by ThomasMarwitzQC** [comment]
Checking out the feedstock and running `conda build recipe -m .ci_support/osx_arm64_python3.12.____cpython.yaml -c conda-forge` locally on osx-arm64 works perfectly fine. 

I can then `conda create -n "local-pynng" --use-local pynng` and import pynng without any problems.

It, therefore, seems to me that the problem with the conda-forge packaged version is due to cross-compilation.

**Comment by ThomasMarwitzQC** [comment]
The problem most certainly lies here:

```
arm64-apple-darwin20.0.0-clang -fno-strict-overflow -DNDEBUG -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -arch arm64 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -arch arm64 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/pynng_1705669622872/work=/usr/local/src/conda/pynng-0.8.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -mmacosx-version-min=11.0 -I/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_build_env/include/nng -I/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.12 -c build/temp.macosx-11.0-arm64-cpython-312/pynng._nng.c -o build/temp.macosx-11.0-arm64-cpython-312/build/temp.macosx-11.0-arm64-cpython-312/pynng._nng.o
  arm64-apple-darwin20.0.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -L/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -L/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -L/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/pynng_1705669622872/work=/usr/local/src/conda/pynng-0.8.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -mmacosx-version-min=11.0 build/temp.macosx-11.0-arm64-cpython-312/build/temp.macosx-11.0-arm64-cpython-312/pynng._nng.o /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_build_env/lib/libnng.dylib /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_build_env/lib/libmbedtls.dylib -lpthread -o build/lib.macosx-11.0-arm64-cpython-312/pynng/_nng.abi3.so
  ld: warning: -pie being ignored. It is only used when linking a main executable
  ld: warning: ignoring file /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_build_env/lib/libnng.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
  ld: warning: ignoring file /Users/runner/miniforge3/conda-bld/pynng_1705669622872/_build_env/lib/libmbedtls.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

where the dynamic libraries (`libnng.dylib` and `libmbedtls.dylib`) are built for macOS-x86_64 instead of osx-arm64. 

This is due to the misplacement of `nng` and `mbedtls` in the `build` section in the `meta.yml`. I previously added these dependencies there because I used the incorrect prefix `CONDA_PREFIX` which would point to the **build** environment, not the host environment. The dependencies there are therefore built for macOS-x86_64. Adjusting the prefix to `PREFIX` and removing the libraries from `build` are done in #25.
